app = "the-vineyard"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  PORT = "3000"
  NODE_ENV = "production"

[[mounts]]
  source = "vineyard_data"
  destination = "/app/data"
